const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('api', {
  minimize: () => ipcRenderer.send('window-minimize'),
  maximize: () => ipcRenderer.send('window-maximize'),
  close: () => ipcRenderer.send('window-close'),
  loadAccounts: () => ipcRenderer.invoke('accounts:load'),
  addAccount: (a) => ipcRenderer.invoke('accounts:add', a),
  removeAccount: (id) => ipcRenderer.invoke('accounts:remove', id),
  updateAccount: (id, data) => ipcRenderer.invoke('accounts:update', id, data),
  reorderAccounts: (ids) => ipcRenderer.invoke('accounts:reorder', ids),
  loadPackages: () => ipcRenderer.invoke('packages:load'),
  savePackages: (packages) => ipcRenderer.invoke('packages:save', packages),
  openLogin: () => ipcRenderer.invoke('roblox:openLogin'),
  cancelLogin: () => ipcRenderer.send('login:cancel'),
  validateCookie: (cookie) => ipcRenderer.invoke('roblox:validateCookie', cookie),
  setRobloxVolume: (percent) => ipcRenderer.invoke('roblox:setVolume', percent),
  killAllRoblox: () => ipcRenderer.invoke('roblox:killAll'),
  killOneRoblox: (id) => ipcRenderer.invoke('roblox:killOne', id),
  getRunningCount: () => ipcRenderer.invoke('roblox:runningCount'),
  onAllRobloxClosed: (cb) => ipcRenderer.on('roblox:allClosed', () => cb()),
  launchRoblox: (id, cookie, target) => ipcRenderer.invoke('roblox:launch', id, cookie, target),
  openExternal: (url) => ipcRenderer.send('open-external', url),
  loadSettings: () => ipcRenderer.invoke('settings:load'),
  saveSettings: (data) => ipcRenderer.invoke('settings:save', data),
  encStatus: () => ipcRenderer.invoke('enc:status'),
  encUnlock: (pass) => ipcRenderer.invoke('enc:unlock', pass),
  encSetKey: (pass) => ipcRenderer.invoke('enc:setKey', pass),
  multiInstanceStatus: () => ipcRenderer.invoke('multiinstance:status'),
  antiAfkStatus: () => ipcRenderer.invoke('antiafk:status'),
  readGenHistory: () => ipcRenderer.invoke('genhistory:read'),
  writeGenHistory: (list) => ipcRenderer.invoke('genhistory:write', list),
  clearGenHistory: () => ipcRenderer.invoke('genhistory:clear'),
  readFFlags: () => ipcRenderer.invoke('fflag:read'),
  writeFFlags: (flags) => ipcRenderer.invoke('fflag:write', flags),
  readFpsCap: () => ipcRenderer.invoke('fps:read'),
  writeFpsCap: (cap) => ipcRenderer.invoke('fps:write', cap),
  onChromeProgress: (cb) => ipcRenderer.on('chrome:download-progress', (_, data) => cb(data)),
  onRobloxClosed: (cb) => ipcRenderer.on('roblox:closed', (_, id) => cb(id)),
  onRobloxCount: (cb) => ipcRenderer.on('roblox:count', (_, n) => cb(n)),
  onLogEntry: (cb) => ipcRenderer.on('log:entry', (_, data) => cb(data)),
  getRobloxVersion: () => ipcRenderer.invoke('roblox:getVersion'),
  getGameName: (placeId, cookie) => ipcRenderer.invoke('roblox:getGameName', placeId, cookie),
});
